"""add_multilingual_and_product_images

Revision ID: b883ca2ae261
Revises: d2466781c998
Create Date: 2026-06-01 00:44:02.705742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b883ca2ae261'
down_revision = 'd2466781c998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('image_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name_hi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_hi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('features_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('features_hi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specifications_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specifications_hi', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('specifications_hi')
        batch_op.drop_column('specifications_en')
        batch_op.drop_column('features_hi')
        batch_op.drop_column('features_en')
        batch_op.drop_column('description_hi')
        batch_op.drop_column('description_en')
        batch_op.drop_column('name_hi')
        batch_op.drop_column('name_en')

    op.drop_table('product_images')
    # ### end Alembic commands ###
