"""add_missing_user_columns

Revision ID: d2466781c998
Revises: d6e929983bfe
Create Date: 2026-06-01 00:03:14.681026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2466781c998'
down_revision = 'd6e929983bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resend_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temporary_user_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('identifier'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('otp')
        batch_op.drop_column('identifier')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['provider_id'])
        batch_op.create_unique_constraint(None, ['microsoft_id'])
        batch_op.drop_column('name')
        batch_op.drop_column('mobile')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('mobile', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('microsoft_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('phone')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('otp', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('identifier'), ['identifier'], unique=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('temporary_user_data')
        batch_op.drop_column('resend_attempts')
        batch_op.drop_column('attempts')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
