"""remove_kannada_support

Revision ID: dbe7576bf300
Revises: b883ca2ae261
Create Date: 2026-06-01 09:33:14.168392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbe7576bf300'
down_revision = 'b883ca2ae261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('features_kn')
        batch_op.drop_column('name_kn')
        batch_op.drop_column('description_kn')
        batch_op.drop_column('specifications_kn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specifications_kn', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description_kn', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name_kn', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('features_kn', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
